### ISSUE TITLE
router problems : Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jmls** [sibartlett/express.oi#2]
so, I found your fork when trying to get express.io working ;)

However, I still have a problem with my existing express app

``` javascript
var express    = require('express.oi');        // call express
var app        = express();                 // define our app using express
var bodyParser = require('body-parser');

app.use(bodyParser.urlencoded({ extended: true }));
app.use(bodyParser.json());
var router = express.Router();              
router.get('/', function(req, res) {
    res.json({ message: 'hooray! welcome to our api!' });
});

app.use('/api', router);
app.listen(3000);
```

this simple app crashes out with :

``` javascript
(null):0
(null)

RangeError: Maximum call stack size exceeded

```

**Comment by sibartlett** [comment]
I have found the source of the bug, for the time-being you need to use the following line:

```
var app        = express().http();
```

To enable both http and socket.io, you should use:

```
var app        = express().http().io();
```

**Comment by jmls** [comment]
um, awesome response time there .. and as a bonus, your workaround, well, works ;)

many thanks

**Comment by sibartlett** [comment]
I fixed the "Maximum call stack size exceeded" error, but the code I gave in my previous comment is the recommended usage in order to use the socket.io functionality.
