### ISSUE TITLE
Startup app fails

### ISSUE THREAD

**Issue by kevkha** [sibartlett/express.oi#3]
I am using express.oi module with NW.js. Any ideas why this is failing?

``` javascript
var express = require('express.oi');

var app = express();

// Pass in your express-session configuration
app.io.session({
  secret: 'express.oi makes me happy'
});

app.http().io();

app.listen(3000);
```

``` javascript
C:\myApp>node app.js
C:\myApp\app.js:6
app.io.session({
       ^
TypeError: undefined is not a function
    at Object.<anonymous> (C:\myApp\app.js:6:8)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
```

**Comment by Shold** [comment]
app.http().io() must be before app.io.session!!!
In .io() function you are create app.io object

**Comment by ghost** [comment]
app.http().io() must be before app.io.session
In .io() function you are create app.io object

**Comment by kevkha** [comment]
Thanks. That works. I copied exactly from <b>Usage > Setting up the app</b>. I will request a change.

**Comment by sibartlett** [comment]
@kevkha sorry about the confusion! I've updated example in the README.

**Comment by kevkha** [comment]
Thanks @sibartlett! Much appreciated. Can you give an example of both server and client? I got the server part from the readme but not sure how to in the client side. Thanks in advance.

**Comment by ghost** [comment]
@kevkha 

Server side route

``` javascript
app.io.route('tests', {
  test: function(req) {
    req.socket.emit('someEvent', 'Some text or JSON string or ....');
  }
});
```

Client side

``` html
...
<script src="pathTo/socket.io-client/socket.io.js"></script>
<script>
    var socket = io.connect();
    socket.on('someEvent', function(data){
        console.log(data);
    });
    socket.emit('tests:test');
</script>
...
```

Don't forget to install socket.io-client i.e. with bower (`bower install socket.io-client`)

**Comment by kevkha** [comment]
Thanks @Shold. If I <code>npm install socket.io-client --save</code> I have to require it in client side instead of calling the socket.io.js correct?

**Comment by ghost** [comment]
@kevkha Yes, socket.io.js from socket.io-client. About npm and bower [SO answer](http://stackoverflow.com/questions/21198977/difference-between-grunt-npm-and-bower-package-json-vs-bower-json/21199026#21199026)

**Comment by sibartlett** [comment]
You only need to install socket.io-client from npm or bower if you want to bundle/precompile the file yourself.

express.oi will serve the client at `/socket.io/socket.io.js` by default.

**Comment by ghost** [comment]
@sibartlett lol Thanks for integrated client!

**Comment by kevkha** [comment]
I learn that many different ways of doing things. It would be less confusion if a working example is provided in the readme or wiki :) Thanks guys.
