### ISSUE TITLE
Forwarding express routes not working

### ISSUE THREAD

**Issue by ghost** [sibartlett/express.oi#5]
Condition in lib/index.js on row 55 is not needed. All routes in app are parsed. IO route `messages: {message: ...}` already "messages:message" in `this.router` and requested route no need to split by `:`.

**Comment by sibartlett** [comment]
@Shold could you provide a small code sample? I've got some time now to look into this.

**Comment by sibartlett** [comment]
@Shold no worries, I have been able to reproduce this!

**Comment by ghost** [comment]
http://pix.toile-libre.org/upload/original/1430420146.png This construction is not working because `tests` is not a object with 2 params test1 and test2 in `this.router`. We have `tests:test1` and `tests:test2`. Therefore we do not need to split requested route `tests:test1`. Sorry for my english. I hope you understand me

**Comment by ghost** [comment]
that's what I mean (lib/index.js): http://pix.toile-libre.org/upload/original/1430420720.png

**Comment by sibartlett** [comment]
I have published a new version to NPM - could you try it please?

**Comment by ghost** [comment]
Yeah! Forwarding now work! Thanks! I will continue testing
