### ISSUE TITLE
Socket routes response

### ISSUE THREAD

**Issue by ghost** [sibartlett/express.oi#6]
- ~~Response to socket `req.io.emit` declared but `req.socket.emit` works.~~ Sorry, I'm wrong about declaration
- In routes for socket `res.json` declared but I don't understand how it works because response to socket-request must be `req.socket.emit` or `broadcast`...

**Comment by sibartlett** [comment]
`res.json` sends an acknowledgement to the client. This functionality is documented on the socket.io website [here](http://socket.io/docs/#sending-and-getting-data-%28acknowledgements%29).

So this in express.oi:

``` js
app.io.route('messages', {
  get: function(req, res) {
    var messageId = req.data.messageId;
    db.messages.get(messageId, function(message) {
      res.json(message);
    });
  }
});
```

is the equivalent to the following in plain socket.io:

``` js
socket.on('messages:get', function(data, fn) {
    var messageId = data.messageId;
    db.messages.get(messageId, function(message) {
      fn(message);
    });
};
```

**Comment by ghost** [comment]
Of course, response object can be used as callback caller. Thanks!
