### ISSUE TITLE
Deprecated express-session

### ISSUE THREAD

**Issue by spamguy** [sibartlett/express.oi#7]
Consider this server:

```
var seekrits = require('./config/local.env');

var express = require('express.oi');
var bodyParser = require('body-parser');

var app = express();
app.use(bodyParser.urlencoded({ extended: false }));
app.use(bodyParser.json());

app.http().io();
app.io.session({
    secret: seekrits.SESSION_SECRET
});

app.listen(9000, function () {
  console.log('Express server listening on %d', 9000);
});
```

Upon firing this up, I get a couple loggers:

```
Running "express:dev" (express) task
Starting background Express server
Thu, 07 May 2015 18:35:34 GMT express-session deprecated undefined resave option; provide resave option at node_modules/express.oi/lib/index.js:82:22

Running "open:server" (open) task
Thu, 07 May 2015 18:35:34 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at node_modules/express.oi/lib/index.js:82:22
```

**Comment by xbenjii** [comment]
Provide the options like it asks.

```
app.io.session({
    secret: seekrits.SESSION_SECRET,
    resave: false,
    saveUninitialized: true
});
```

**Comment by spamguy** [comment]
Oops! Sorry, the absence of line breaks obfuscated the real errors. Adding those in fixes the problem. Thanks for the quick response.

**Comment by xbenjii** [comment]
You're welcome :) Bare in mind these might not be the options you want, but they're the most popular.

You can read about them [here](https://github.com/expressjs/session#sessionoptions), choose the ones that suit your needs.

**Comment by sibartlett** [comment]
@xbenjii thank you for helping out, I appreciate it a lot! :smile:

**Comment by spamguy** [comment]
BTW, would it make sense to tweak the docs to reflect this? That was what I was working with leading up to this ticket.

**Comment by sibartlett** [comment]
@spamguy thanks for reminding me! I've updated the readme.
