### ISSUE TITLE
Routing via use() doesn't work

### ISSUE THREAD

**Issue by spamguy** [sibartlett/express.oi#8]
Up until today I've been working entirely off a REST API, lumping any commands I need in a separate file [as documented in this article](http://www.terlici.com/2014/09/29/express-router.html).

I am working to get express.io running, and somehow the same setup isn't working. In this minimal example, hitting /api/login results in a 404:
### server.js

```
var express = require('express.oi');

var app = express();

app.use('/api', require('./api/auth'));
app.http().io();

app.listen(9000, function () {
  console.log('Express server listening on %d', 9000);
});
```
### api/auth.js

```
module.exports = function() {
    var express = require('express');
        router = express.Router();

    router.post('/login', function(req, res, next) {
        console.log('hi');
    });
    return router;
};
```

**Comment by sibartlett** [comment]
The following works for me:

### server.js

```
var express = require('express.oi');

var app = express();

app.use('/api', require('./api/auth')());

app.http().io();

app.listen(9000, function () {
  console.log('Express server listening on %d', 9000);
});
```

### api/auth.js

```
module.exports = function() {
    var express = require('express.oi');
        router = express.Router();

    router.get('/login', function(req, res) {
        res.json({message: 'hello'});
    });

    return router;
};
```

**Comment by sibartlett** [comment]
@spamguy is this for your Diplomacy game? I've been working on a node.js version of Catan!

**Comment by spamguy** [comment]
@sibartlett Thanks, that makes sense. Will try this in a couple hours and get back to you.

Yes, it is for my [Diplomacy game](http://dipl.io). I'm thrilled to see another game-to-Node developer. I will definitely keep an eye on your efforts.

**Comment by spamguy** [comment]
Works out. Thanks!
