### ISSUE TITLE
app.io.routes session 

### ISSUE THREAD

**Issue by patrykwegrzyn** [sibartlett/express.oi#9]
Looks like session object is not available in io routes ? 

``` javascript
app.io.route('ready', function(req) {
    console.log('req.session',req.session)   -> req.session undefined
})
```

Worked like a  charm with express.io
Please advice

**Comment by DemersM** [comment]
same problem for me. Did you find a solution ? If yes, can you post your app configuration?

**Comment by benkaiser** [comment]
bump

**Comment by ghost** [comment]
@patrykwegrzyn @DemarsM @benkaiser 
Project is not supported more than 6 months (( I'll try to continue it here: https://github.com/Shold/express.oi
io.session fixed

**Comment by sibartlett** [comment]
@Shold thanks for taking a look into this, I can merge the changes and release to NPM.

**Comment by ghost** [comment]
I'm publish NPM too ((( Sorry

**Comment by sibartlett** [comment]
@Shold I merged your changes in, and published anyway.
